In [1]:
import pandas as pd

In [2]:
df = pd.read_csv('players_20.csv')
df.set_index('short_name', inplace = True)
df = df[['long_name','age','dob', 'height_cm','weight_kg','nationality','club']]
df

,long_name,age,dob,height_cm,weight_kg,nationality,club
short_name,,,,,,,
L. Messi,Lionel Andrés Messi Cuccittini,32,1987-06-24,170,72,Argentina,FC Barcelona
Cristiano Ronaldo,Cristiano Ronaldo dos Santos Aveiro,34,1985-02-05,187,83,Portugal,Juventus
Neymar Jr,Neymar da Silva Santos Junior,27,1992-02-05,175,68,Brazil,Paris Saint-Germain
J. Oblak,Jan Oblak,26,1993-01-07,188,87,Slovenia,Atlético Madrid
E. Hazard,Eden Hazard,28,1991-01-07,175,74,Belgium,Real Madrid
...,...,...,...,...,...,...,...
Shao Shuai,邵帅,22,1997-03-10,186,79,China PR,Beijing Renhe FC
Xiao Mingjie,Mingjie Xiao,22,1997-01-01,177,66,China PR,Shanghai SIPG FC
Zhang Wei,张威,19,2000-05-16,186,75,China PR,Hebei China Fortune FC
Wang Haijian,汪海健,18,2000-08-02,185,74,China PR,Shanghai Greenland Shenhua FC
Pan Ximing,潘喜明,26,1993-01-11,182,78,China PR,Hebei China Fortune FC

# Copy()

## deep = True

In [3]:
# deep = True by default (Modifications to the data or indices of the copy)
df_copy() = df.copy()

SyntaxError: cannot assign to function call here. Maybe you meant '==' instead of '='? (3635535136.py, line 2)

In [4]:
#update value in original dataframe
df.loc['L. Messi', 'height_cm'] = 180

In [7]:
df

,long_name,age,dob,height_cm,weight_kg,nationality,club
short_name,,,,,,,
L. Messi,Lionel Andrés Messi Cuccittini,32,1987-06-24,180,72,Argentina,FC Barcelona
Cristiano Ronaldo,Cristiano Ronaldo dos Santos Aveiro,34,1985-02-05,187,83,Portugal,Juventus
Neymar Jr,Neymar da Silva Santos Junior,27,1992-02-05,175,68,Brazil,Paris Saint-Germain
J. Oblak,Jan Oblak,26,1993-01-07,188,87,Slovenia,Atlético Madrid
E. Hazard,Eden Hazard,28,1991-01-07,175,74,Belgium,Real Madrid
...,...,...,...,...,...,...,...
Shao Shuai,邵帅,22,1997-03-10,186,79,China PR,Beijing Renhe FC
Xiao Mingjie,Mingjie Xiao,22,1997-01-01,177,66,China PR,Shanghai SIPG FC
Zhang Wei,张威,19,2000-05-16,186,75,China PR,Hebei China Fortune FC
Wang Haijian,汪海健,18,2000-08-02,185,74,China PR,Shanghai Greenland Shenhua FC
Pan Ximing,潘喜明,26,1993-01-11,182,78,China PR,Hebei China Fortune FC

## deep = False

In [10]:
# deep = false (Any changes to the data of the original will be reflected
# in the shallow copy and vice versa, means all the changes that we do in df will reflect to df_copy())
df_copy = df.copy(deep = False)

In [11]:
#update value in original data 
df.loc['Cristiano Ronaldo', 'height_cm'] = 200

In [12]:
#shallow copy vs original dataframe
df

,long_name,age,dob,height_cm,weight_kg,nationality,club
short_name,,,,,,,
L. Messi,Lionel Andrés Messi Cuccittini,32,1987-06-24,180,72,Argentina,FC Barcelona
Cristiano Ronaldo,Cristiano Ronaldo dos Santos Aveiro,34,1985-02-05,200,83,Portugal,Juventus
Neymar Jr,Neymar da Silva Santos Junior,27,1992-02-05,175,68,Brazil,Paris Saint-Germain
J. Oblak,Jan Oblak,26,1993-01-07,188,87,Slovenia,Atlético Madrid
E. Hazard,Eden Hazard,28,1991-01-07,175,74,Belgium,Real Madrid
...,...,...,...,...,...,...,...
Shao Shuai,邵帅,22,1997-03-10,186,79,China PR,Beijing Renhe FC
Xiao Mingjie,Mingjie Xiao,22,1997-01-01,177,66,China PR,Shanghai SIPG FC
Zhang Wei,张威,19,2000-05-16,186,75,China PR,Hebei China Fortune FC
Wang Haijian,汪海健,18,2000-08-02,185,74,China PR,Shanghai Greenland Shenhua FC
Pan Ximing,潘喜明,26,1993-01-11,182,78,China PR,Hebei China Fortune FC

# Simple Assignment

In [13]:
#make a copy
df_new_copy = df

In [14]:
df.loc['Neymar Jr', 'height_cm'] = 200

In [16]:
df

,long_name,age,dob,height_cm,weight_kg,nationality,club
short_name,,,,,,,
L. Messi,Lionel Andrés Messi Cuccittini,32,1987-06-24,180,72,Argentina,FC Barcelona
Cristiano Ronaldo,Cristiano Ronaldo dos Santos Aveiro,34,1985-02-05,200,83,Portugal,Juventus
Neymar Jr,Neymar da Silva Santos Junior,27,1992-02-05,200,68,Brazil,Paris Saint-Germain
J. Oblak,Jan Oblak,26,1993-01-07,188,87,Slovenia,Atlético Madrid
E. Hazard,Eden Hazard,28,1991-01-07,175,74,Belgium,Real Madrid
...,...,...,...,...,...,...,...
Shao Shuai,邵帅,22,1997-03-10,186,79,China PR,Beijing Renhe FC
Xiao Mingjie,Mingjie Xiao,22,1997-01-01,177,66,China PR,Shanghai SIPG FC
Zhang Wei,张威,19,2000-05-16,186,75,China PR,Hebei China Fortune FC
Wang Haijian,汪海健,18,2000-08-02,185,74,China PR,Shanghai Greenland Shenhua FC
Pan Ximing,潘喜明,26,1993-01-11,182,78,China PR,Hebei China Fortune FC

In [17]:
df_new_copy

,long_name,age,dob,height_cm,weight_kg,nationality,club
short_name,,,,,,,
L. Messi,Lionel Andrés Messi Cuccittini,32,1987-06-24,180,72,Argentina,FC Barcelona
Cristiano Ronaldo,Cristiano Ronaldo dos Santos Aveiro,34,1985-02-05,200,83,Portugal,Juventus
Neymar Jr,Neymar da Silva Santos Junior,27,1992-02-05,200,68,Brazil,Paris Saint-Germain
J. Oblak,Jan Oblak,26,1993-01-07,188,87,Slovenia,Atlético Madrid
E. Hazard,Eden Hazard,28,1991-01-07,175,74,Belgium,Real Madrid
...,...,...,...,...,...,...,...
Shao Shuai,邵帅,22,1997-03-10,186,79,China PR,Beijing Renhe FC
Xiao Mingjie,Mingjie Xiao,22,1997-01-01,177,66,China PR,Shanghai SIPG FC
Zhang Wei,张威,19,2000-05-16,186,75,China PR,Hebei China Fortune FC
Wang Haijian,汪海健,18,2000-08-02,185,74,China PR,Shanghai Greenland Shenhua FC
Pan Ximing,潘喜明,26,1993-01-11,182,78,China PR,Hebei China Fortune FC